### ISSUE TITLE
Route: Signup with JWT

### ISSUE THREAD

**Issue by kavania2002** [Programming-Club-Ahmedabad-University/TheProgrammingClub#10]
## Context
Create a route ```/api/auth/signup```

## Todo
A signin route must be create at the given route. It should give back a JWT token.
The return JSON should be of ```{user: userCreated}``` form.

## Additional Reference
https://www.section.io/engineering-education/how-to-build-authentication-api-with-jwt-token-in-nodejs/

**Comment by BhagatHarsh** [comment]
I would like to work on this issue.
Please clarify on the JSON object that is needed to be returned. also where should the bcrypt functions go, should i just put them inside the */api/auth/signup* route file.

**Comment by kavania2002** [comment]
@BhagatHarsh 
It should return an JSON object like this
```
{
    token: "oaheroheaoruh", // the JWT token created
    user: { all the attributes from the user model} // the user data which gets stored in the DB
}
```
