### ISSUE TITLE
Backend: add cors to server

### ISSUE THREAD

**Issue by kavania2002** [Programming-Club-Ahmedabad-University/TheProgrammingClub#11]
## Context
Needed to connect with Frontend.

## Todo
Adding cors npm package and its config.
Read articles on why CORS is needed to be set up in the backend.

**Comment by im3dabasia** [comment]
can I work on this issue?

**Comment by jeetb2022** [comment]
can i work on this issue ?

**Comment by Maulik176** [comment]
@im3dabasia You are already working on one. Would you be comfortable working on both?

**Comment by Maulik176** [comment]
@jeetb2022 I've assigned you the same

**Comment by mirchandani-mohnish** [comment]
The issue seems closed and thus redundant. Thanks a lot
